### ISSUE TITLE
How to integrate with Interactive Brokers for testing with Paper trading

### ISSUE THREAD

**Issue by developeralgo8888** [AdrianP-/gym_trading#1]
Adrian is possible for you to put together a notebook to integrate it with IB for paper trading or demo trading in a simple  realtime test environment

**Comment by AdrianP-** [comment]
Hi, I've never worked with IB API, so I don't know how can do it and related problems. However the next big step is integrate this project with a better backend (Zipline, pyAlgoTrade, or even IB). But I found several problems with these frameworks. E.g Zipline, hasn't forex, complex integrations etc.
I will take a look

**Comment by agentmartynas1** [comment]
Hi, I am a co-founder of an EU based FX/CFD and Derivatives brokerage. I could arrange for the necessary APIs and market data to setup some meaningful tests. Also could point you in the right direction for equities other trading access.
