### ISSUE TITLE
difference between reward and profit

### ISSUE THREAD

**Issue by StrikerRUS** [AdrianP-/gym_trading#4]
Hi @AdrianP- !

First of all, many thanks for this repo! For me, it's the clearest and features-rich at the same time among many other trading gyms.

Sorry for using issues for asking the questing, but I haven't found any contacts on your GitHub page.

Can you please clarify the difference between `reward` and `Profit`?

**Comment by AdrianP-** [comment]
Hi @StrikerRUS , thanks to you :) 
`reward` it's the result of a function necessary for the reinforcement algorithm. In this function, you define whatever you want depending on your problem/environment- and the algorithm will maximize/minimize the result (`reward`)
In the typical stock trading algorithm, you want to maximize the `profit`, for this reason, the `profit` is the `reward`

**Comment by StrikerRUS** [comment]
@AdrianP- Thanks for the prompt response!

From your words I got that `reward == profit`, and in logs we could replace one with another, right?

Also I have another question: does `_generate_summary_stats()` show the statistics of the **last** episode of training stage? Or what?..
https://github.com/AdrianP-/gym_trading/blob/af5767a469db550459517e10c439df1c8764aa86/gym_trading/envs/trading_env.py#L41
Because according the logs from the repo's notebook it's not true:
```
steps                     | 299459
episodes                  | 140
% time spent exploring    | 2
--
mean episode reward       | 197.2
Total operations          | 93
Avg duration trades       | 21.28
Total profit              | 99.0  <------------------------
Avg profit per trade      | 1.421
--
Total profit test:        > -260.8
Avg profit per trade test > -11.521
-------------------------------------
SUMMARY STATISTICS
Total Trades Taken:  14
Total Reward:  347.3  <------------------------
Average Reward per Trade:  24.8071428571
Win Ratio: 71.4285714286 %
```

**UPD:**
Also I've noticed the main difference between `Profit` and `reward`: `Profit` is calculated as, let say, real profit in the real world, like delta of exit and entry prices of the **current trade**, while the `reward` calculation is based on **current time** prices.

**Comment by AdrianP-** [comment]
Exactly as you said in the update, you can write the function `reward` as the mean of each profit (as it is now, mean of the last 100 operations) or profit per trade (you want to maximize each trade, not global).

`_generate_summary_stats` function is called when the episode is solved or at the end of the episode. Episode is `(np.mean(episode_rewards[-101:-1]) > 500 or t >= 10000) and len(env.portfolio.journal) != 0`

**Comment by StrikerRUS** [comment]
Thanks for the answer!
But if I'm not mistaken, episode is a 1 full iteration over the train part of the file, and the condition you've mentioned is used to check whether the training is over, doesn't it?

**Comment by jalalmzh** [comment]
hi @AdrianP
I want to execute "Baseline DQN Gym_Trading Tutorial.ipynb" in step3 

" env = gym.make('trading-v0')
env.initialise_simulator(csv, trade_period=50, train_split=0.7) "

get error below 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-157a89628c14> in <module>()
----> 1 env = gym.make('trading-v0')
      2 env.initialise_simulator(csv, trade_period=50, train_split=0.7)

C:\Anaconda3\lib\site-packages\gym\envs\registration.py in make(id)
    165 
    166 def make(id):
--> 167     return registry.make(id)
    168 
    169 def spec(id):

C:\Anaconda3\lib\site-packages\gym\envs\registration.py in make(self, id)
    123         # compatibility code to be invoked.
    124         if hasattr(env, "_reset") and hasattr(env, "_step") and not getattr(env, "_gym_disable_underscore_compat", False):
--> 125             patch_deprecated_methods(env)
    126         if (env.spec.timestep_limit is not None) and not spec.tags.get('vnc'):
    127             from gym.wrappers.time_limit import TimeLimit

C:\Anaconda3\lib\site-packages\gym\envs\registration.py in patch_deprecated_methods(env)
    183     env.reset = env._reset
    184     env.step  = env._step
--> 185     env.seed  = env._seed
    186     def render(mode):
    187         return env._render(mode, close=False)

AttributeError: 'TradingEnv' object has no attribute '_seed'
----------------------------------------------------------------------------
why I did get that? and how do I fix it?

**Comment by StrikerRUS** [comment]
@jalalmzh Please see #3 and next time create your own issue.
